SD-310-W22D-Assignment/SD-310-W22D-Assignment/Controllers/SongController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SD_310_W22D_Assignment.Models;
using SD_310_W22D_Assignment.Models.ViewModels;


namespace SD_310_W22D_Assignment.Controllers
{
    public class SongController : Controller
    {
        private MyTunesContext _dbContext;
        public SongController(MyTunesContext context)
        {
            _dbContext = context;
        }

        public IActionResult Index(int? artistId)
        {
            try
            {
                // find artist 
                var artistName =
                    from artist in _dbContext.Artists
                    where artist.Id == artistId
                    select artist.Name;

                if (artistId != null)
                {
                    return View(artistName);
                }
                else
                {
                    throw new Exception("Artist not found");
                }

            }
            catch (Exception ex)
            {
                return RedirectToAction("Error");
            }
        }

        public IActionResult Index()
        {
            SongSelectViewModel vm = new SongSelectViewModel(_dbContext.Songs.ToList());
            return View();
        }

        public IActionResult Error()
        {
            return View();
        }
    }
}

SD-310-W22D-Assignment/SD-310-W22D-Assignment/Controllers/UsersController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SD_310_W22D_Assignment.Models;

namespace SD_310_W22D_Assignment.Controllers
{  public class UsersController : Controller
    {
        private MyTunesContext _dbContext;
        public UsersController(MyTunesContext context)
        {
            _dbContext = context;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Add()
        {
            return View();
        }
    }
}

SD-310-W22D-Assignment/SD-310-W22D-Assignment/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SD_310_W22D_Assignment</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SD_310_W22D_Assignment.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MyTunes</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Song" asp-action="Index">Artist</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Index">Users</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - SD_310_W22D_Assignment - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>